### ISSUE TITLE
⭐️[FEATURE] As a passport holder, I want to be informed of when my passport is ready to be interactive

### ISSUE THREAD

**Issue by brentmartin** [gitcoinco/dPopp#102]
GIVEN that I am creating or revisiting my passport
WHEN the page is still loading
THEN I expect some sort of indication that the page is still loading
AND I can only interact with the page once the passport is fully loaded and created 
AND the page is disabled until the passport is fully loaded and created

**Notes**

- takes ~4 to 5 seconds to load
- this will happen both when I am creating & loading AND when I am revisiting & loading
- we want to prevent the action of users clicking on stamps before passport is loaded
- pulse state for the page while it loads
- https://tailwindcss.com/docs/animation
- https://codepen.io/muratbenli/pen/yLOYmgj

**Comment by shavinac** [comment]
Addressed by [fix(app): adds intermediate loading state to stamp verify buttons](https://github.com/gitcoinco/dPopp/commit/1e54adcdd1b7b1b05d4869f013a94b7a381ee8c3)
