### ISSUE TITLE
[CHORE] [PROD READINESS] Switch Facebook app from development -> live

### ISSUE THREAD

**Issue by yonocan** [gitcoinco/dPopp#105]
**Notes**
- this is part of the developer checklist for Facebook
- we need to submit public URL's
- for submitting terms and privacy to Facebook - use `https://gitcoin.co/terms` , `https://gitcoin.co/legal/privacy`

**Comment by shavinac** [comment]
Facebook app is live for now, will be addressing legal compliance checking / lookover / etc later on
