### ISSUE TITLE
[CHORE] Add a prod domain and configure DNS

### ISSUE THREAD

**Issue by yonocan** [gitcoinco/dPopp#106]
**Gitcoin Passport webapp now available at: https://passport.gitcoin.co/**

**Notes**
- will be using `passport.gitcoin.co`
- we want to take the fastest path to use a URL
- would need a new URL for longterm plan with a rebrand

#### For GR14
dPopp for GR14 = `passport.gitcoin.co`
Reader on Trust Bonus = `gitcoin.co/trust`

Dev notes
- can set Fleek to use custom domain - see [docs](https://docs.fleek.co/domain-management/custom-dns-domains/)
- may need to set up fleek paid plan before we run out of bandwidth in prod
- still using ceramic testnet, until our self-hosted mainnet node is up & running

**Comment by shavinac** [comment]
realized we need to switch around some DNS records of gitcoin.co 😓  on-hold until those get switched over
