### ISSUE TITLE
[CHORE] Create a prod release of v1.0.0

### ISSUE THREAD

**Issue by yonocan** [gitcoinco/dPopp#109]
Reminder to set a version on this - for devs for versioning reasons
new name - `passport-app`?

**Notes from IPM**
- Spin up new repository with clean history
- Pull back current repo to private 
- June 6th or June 7th

**Comment by brentmartin** [comment]
Add all of the SDK work into this versioning - @gdixon for more details

**Comment by shavinac** [comment]
@leoneric - should we keep the same repo, or create a new one with clean history?
* if we keep the same repo, people can see our whole development history
* if we create a new repo, the community PRs (coinbase, discord, linkedin stamps) and community-reported issues would not be carried over
