### ISSUE TITLE
🚗 [GRANTS] As a Gitcoin user, I want to know what steps I need to complete to create and score my passport

### ISSUE THREAD

**Issue by yonocan** [gitcoinco/dPopp#122]
GIVEN that I am Gitcoin user with a Gitcoin account
WHEN I am on the Trust Bonus page 
THEN I see a button that tells me to "Create Passport" 
AND WHEN I have a passport and I click that button 
THEN the button changes to "Score Passport" AND step 1 is marked as completed with a check 

AND WHEN I do not have a passport created 
THEN I am redirected to passport.gitcoin.co (can we do this??)

AND WHEN I click "Score Passport" 
THEN I see a score appear AND the button changes to "Save Passport" AND step is marked as completed
AND WHEN I click "Save Passport"
THEN my score is saved to Gitcoin.co AND step 3 is marked as completed 

**Figma Files**
Links
- https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=2234%3A45211
- https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=2227%3A45176
- https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=2227%3A45363

Screenshot: 
![Image](https://user-images.githubusercontent.com/5656217/171468227-e7c10a87-fe1a-4d04-a01e-1f028be0bb94.png)

**Comment by yonocan** [comment]
Marking this story as accepted. We did change the buttons to account for the actual states that are happening: connect, score, save. 

There are additional changes to improve this experience, but those are part of #130

@brentmartin

**Comment by brentmartin** [comment]
great context for #130 - looks great to me 👍
