### ISSUE TITLE
🚗 [GRANTS] As a user, I want to be redirected to the Gitcoin Passport production site instead of the review site

### ISSUE THREAD

**Issue by yonocan** [gitcoinco/dPopp#129]
GIVEN that I have a Gitcoin account
WHEN I click on "Go to Gitcoin Passport"
THEN I should be taken to passport.gitcoin.co

**Comment by yonocan** [comment]
The link "Got to Gitcoin Passport" took me to the production site: passport.gitcoin.co. I consider this story tested and accepted @brentmartin

**Comment by brentmartin** [comment]
Awesome - this one is simple.  Send it 👍
