### ISSUE TITLE
🚗 [GRANTS] As a Gitcoin user, I want to rescore my passport

### ISSUE THREAD

**Issue by yonocan** [gitcoinco/dPopp#130]
GIVEN that I am a Gitcoin user AND I have connected a passport to Gitcoin.co
WHEN I click "Score Passport"
THEN a drawer opens and I see the option to save my passport
AND WHEN I save my passport
THEN a drawer opens and I see the option to "refresh passport" to re-score my passport

**Mocks**
- https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=2262%3A47876
- https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=2268%3A45321
- https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=2268%3A45441
- https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=2268%3A45574

**Comment by brentmartin** [comment]
I believe these are already on production, right?
