### ISSUE TITLE
[CHORE]: Front-end logging aggregation

### ISSUE THREAD

**Issue by dhx12** [gitcoinco/dPopp#139]
Need to clean up and make front-end logging consistent. We should also look into if we can aggregate the logs somewhere for debugging, e.g. Datadog, etc

#### Datadog
- Need Client Token and Application ID (generated in Datadog)
- RUM Browser Monitoring to track user journeys in the app and through the backend
- Browser Log collection can be attached to user sessions and tied to events on the IAM server

**Comment by brentmartin** [comment]
Things to log:
- successful stamps of each
- failures of each stamp
