### ISSUE TITLE
🚗 [GRANTS] As a previous Grants rounds Contributor, I want to know what happened to my existing Trust Bonus Score

### ISSUE THREAD

**Issue by brentmartin** [gitcoinco/dPopp#149]
**Notes**

UI Changes to be made:
✅ Remove Trust Verification header & body text
✅ Move whole page up after body text
✅ Remove subhead under Passport
✅ *Change Header content
✅ *Change body content
✅ Remove the link at bottom (no longer needed)
✅ Change text above bar from "Verification Level" to "Trust Bonus Score"

\* content to replace with coming

**Comment by brentmartin** [comment]
We'll go over this in more detail in IPM - adding in AC at that time as well.

In the meantime, I wanted to add enough direction for @nutrina to get started on this Monday if he has time to before IPM.

For now, I'll add a few screenshots to cover some of the changes.

> - Remove Trust Verification header & body text
![Image](https://user-images.githubusercontent.com/5798446/172104068-b495df78-f147-474a-a16f-bd1c8463eee3.png)

> - Remove subhead under Passport
![Image](https://user-images.githubusercontent.com/5798446/172104144-5da4a687-97d4-462b-9a07-b9376e05be3d.png)

> - Move whole page up after body text
![Image](https://user-images.githubusercontent.com/5798446/172104243-82359fd0-fead-4c53-9947-2951f1cf1fa7.png)

> - Remove the link at bottom (no longer needed)
![Image](https://user-images.githubusercontent.com/5798446/172104892-b6cc42f7-90c4-4fe8-9855-263ce0ae617c.png)

> - Change text above bar from "Verification Level" to "Trust Bonus Score"
![Image](https://user-images.githubusercontent.com/5798446/172104939-dcdd8257-154f-43ab-abe0-bc6420755e29.png)

**Comment by nutrina** [comment]
This is how the result would look like, please comment on this (in case it is not yet deployed for review)

![Image](https://user-images.githubusercontent.com/8137830/172116513-216ad572-3a17-4d94-8cd5-8c87681a9533.png)

**Comment by brentmartin** [comment]
Here's the content for the following changes:

> • Change Header content
![Image](https://user-images.githubusercontent.com/5798446/172312589-9fe02c6a-d8b2-49b0-bf5c-d1ce623fcda1.png)

Change "Passport" to "Trust Bonus"



> • Change body content
![Image](https://user-images.githubusercontent.com/5798446/172313160-ebc91bf3-6b08-4ef2-aaab-1ba710558793.png)

Change:
"The Gitcoin Passport verifies your personhood and strengthens sybil resistance. Trust Bonus Scores are calculated by the identification stamps you complete. The Passport Scorer is fully decentralized on the Ceramic Network."

to:
"Trust Bonus has received an upgrade! It's now powered by Gitcoin Passport, a decentralized identity verification application. Trust Bonus scores are calculated based on the identification stamps you complete. 

Note: If you already have a Trust Bonus score, saving a new one will override your existing score. Be sure to collect all your existing stamps in your new Passport before saving a new score!"

**Comment by brentmartin** [comment]
Looks great to me @nutrina 👍
