### ISSUE TITLE
🎫 [STAMPS] As a passport holder, I can add a Github Stamp to my passport

### ISSUE THREAD

**Issue by brentmartin** [gitcoinco/dPopp#153]
GIVEN that I am logged into my passport
WHEN I click the call to action on the Github stamp
THEN I see a message that ask me to sign in through OAuth
AND WHEN I have successfully sign in through OAuth
THEN my Github stamp shows that I am verified

**Notes**
- if BrightID is not working like we expect, then shipping this would be important for our users

**Comment by nutrina** [comment]
PR is open, waiting for PR approval:

https://github.com/gitcoinco/dPopp/pull/192
