### ISSUE TITLE
🎨 [UI CHORE] Update Trust Bonus Score page Stamps image

### ISSUE THREAD

**Issue by brentmartin** [gitcoinco/dPopp#157]
change the following image out

![Image](https://user-images.githubusercontent.com/100154376/172273096-a454f689-f3d4-446b-98db-378870f0c2b4.png)

**Comment by Etovardesign** [comment]
![Trust Bonus Image](https://user-images.githubusercontent.com/100154376/172440664-94211abb-eff8-4661-a242-15db95b2c4fc.svg)
