### ISSUE TITLE
🎨 [UI CHORE] Error Messaging content for Passport reader on gitcoin.co

### ISSUE THREAD

**Issue by brentmartin** [gitcoinco/dPopp#158]
Make the following updates to the error states:

**[Step 1] Create**
- [Error State - No Passport] needs to say -> "No Passport associated with this wallet."

**[Step 2]: Score**
- [Error State - No Ceramic] needs to say -> "No Ceramic account associated with this wallet."

**[Step 3]: Save**
- [Error State] needs to say -> "A wallet signature is required to score your Passport."
- [Error State] needs to say -> "There was an error; please try again later."

for more details on this content check out - https://docs.google.com/document/d/1JooefHsWus-0UVEx-Lp3OjZ5QhnZ2J1u3pFH_Mc_LG0/edit

**Comment by Etovardesign** [comment]
[Step 1]: Create
Visit Gitcoin Passport to create your proof of personhood and
complete stamps.
[Error State] - No Passport associated with this wallet. 
[Step 2]: Score
Return to present your stamps to Gitcoin and receive a trust bonus score.
[Error State] - No Ceramic account associated with this wallet.
[Step3]: Save
Save your trust bonus score so it is used to calculate your matching amounts.
[Error State]: A wallet signature is required to score your Passport.
[Error State]: There was an error; please try again later.
