### ISSUE TITLE
🎨 [UI CHORE] Update logos on all passport.gitcoin.co pages

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/dPopp#180]
Logo svg: 
![Image](https://user-images.githubusercontent.com/59769856/172832529-ceb28649-544e-4264-aa9f-de979dc2f75f.svg)

@Etovardesign will add a Figma showing the placements of the new logo svg soon.

**Comment by Etovardesign** [comment]
@leoneric @brentmartin 

Desktop: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=2538%3A47129

Mobile: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=2655%3A46790

Note: There is 2 versions of the logo, 1 that works on a white background and 1 that works on a dark background.
