### ISSUE TITLE
🎨 [UI CHORE] Add shout out to Ceramic Network in the footer of all passport.gitcoin.co pages

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/dPopp#181]

**Comment by leoneric** [comment]
@Etovardesign, can you please create Figma files including the Ceramic Network shout out placements on all the Passport pages?

**Comment by Etovardesign** [comment]
@leoneric Figma: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=2538%3A47129
