### ISSUE TITLE
⭐️ [FEATURE] allow users to download their passport JSON from the passport app

### ISSUE THREAD

**Issue by kevinrolsen** [gitcoinco/dPopp#195]
Bypass ceramic and allow users to download the JSON. oftheir passport

As a user of passport
When I have a passport
I want to download my passport data
So that I can be the trusted store of my data

GIVEN that I am a passport holder
WHEN I am viewing my passport
THEN I see the option to download my passport
AND WHEN I click that button
THEN my passport is downloaded as JSON

**Comment by Etovardesign** [comment]
@leoneric Figma: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=2565%3A54352

**Comment by nutrina** [comment]
https://github.com/gitcoinco/dPopp/pull/211

**Comment by nutrina** [comment]
This is done, waiting on PR review before merge.
