### ISSUE TITLE
🚗 [GRANTS] 🎨 [UI] show pending status in the trust bonus page when people submit their passport

### ISSUE THREAD

**Issue by kevinrolsen** [gitcoinco/dPopp#197]
As a user on the trust bonus page
When I submit my passport and save
If I refresh the page 
AND my passport is still being processed in the background
I should see my "passport is being validated" (with the score of my submitted passport)
AND I should not see my old score

**Comment by kevinrolsen** [comment]
Users are getting confused when they submit their passport and getting caught in a loop resubmitting their passport

We need to give some UI feedback that their passport was submitted, and is being processed. 

If a passport fails we should also consider some output to the user TBA in a follow-up ticket.

**Comment by Etovardesign** [comment]
@kevinrolsen @leoneric I put together this mockup where I include a "Passport is being validated" prompt as well as a Submission success state. I hope I'm not understanding it wrong.

Figma: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=2569%3A56600

**Comment by nutrina** [comment]
We also need a new confirmation message when "saving" the trust bonus, because that is not true (it was added to q queue):


![Image](https://user-images.githubusercontent.com/8137830/173795095-5febae20-cc25-4075-89eb-74ec5c73c7e4.png)
