### ISSUE TITLE
🐛 [BUG] all the stamp Tiles have the session key as the controller rather than the DID PKH

### ISSUE THREAD

**Issue by shavinac** [gitcoinco/dPopp#200]
[Ceramic Discord : #gitcoin : oed](https://discord.com/channels/682786569857662976/963185659638607982/985891834280685608)

> FYI, I've also identified a non-critical issue in the app, which should be resolved by upgrading to the latest @ceramicnetwork/stream-tile everywhere in your app.
> Basically all the stamp Tiles have the session key as the controller rather than the DID PKH. This happens right now because the older version of the package mentioned above is not aware of PKH DIDs and session keys.

Impact: stamp streams will not be **updateable** after the session key expires - the data is still readable though.

Fix: upgrading to the latest `@ceramicnetwork/stream-tile` everywhere in the app

**Comment by stbrody** [comment]
Ideally would be good to not just update stream-tile but also the dids, cacao, and any other ceramic-related packages that run client side at the same time

**Comment by shavinac** [comment]
Possibly resolved when https://github.com/gitcoinco/dPopp/pull/249 merged?

**Comment by shavinac** [comment]
Resolved -- stamp tiles now correctly have the user's PKH DID as the controller
