### ISSUE TITLE
Improve queries of genesis content to reduce timeout errors

### ISSUE THREAD

**Issue by shavinac** [gitcoinco/dPopp#201]
Issue: seeing many timeout errors of the format `Timeout error while loading CID baf...` (note `baf...` CIDs indicate deterministic/genesis content, as opposed to `bag...` CIDs)
```
[2022-06-10T20:00:53.733Z] WARNING: Error loading stream k2t6wyfsu4pfz593mwwdnmgrqw1xds3tx6oq9zdkenerkbpyymozofiuztclca at time undefined as part of a multiQuery request: Error: Timeout after 7000ms	ceramic
6/10/2022, 3:00:59 PM	Timeout error while loading CID bafyreick4vazhaj5rnighdh5hpgnrnizi2z7xi3cijklsilorpt5uykftm from IPFS. 2 retries remain	ceramic
```

One root cause would be a reader (e.g. Trust Bonus) attempting to fetch a Passport from a user who has not yet created a Passport - causing a timeout error because the document does not exist yet. (see [#gitcoin channel in ceramic discord](https://discord.com/channels/682786569857662976/963185659638607982/985138864240873472))

> Essentially I'm wondering if you are using the tulons library anywhere?
> https://github.com/tulons/tulons-ts/blob/main/src/tulons.ts#L138-L150
> This code generates the streamId without adding it to your ipfs node. If this is used to query for a stream before the user has used your app, it would result in these timeouts.
> It's possible to load streams based on genesis content using the "create" api: https://developers.ceramic.network/build/http/api/#creating-stream
> So yes, it seems we are using tulons for reading. And in our backend I think we have the similar logic written in python.
> Here's a better way to query something by genesis content using http:
> curl https://your-node.com/api/v0/streams -X POST -d '{
>      "type": 0,
>      "genesis": {
>        "header": {
>          "family": "IDX",
>          "controllers": ["did:pkh:eip155:1:0x4d2dc604c2d44803fb4481cc5283f7cbb462e4f3"]
>        }
>      },
>      "opts": {
>        "pin": true,
>        "sync": true,
>        "anchor": false
>      }
>    }' -H "Content-Type: application/json" | jq

**Comment by oed** [comment]
looks like this app is not using the `tulons` package?

**Comment by shavinac** [comment]
> looks like this app is not using the `tulons` package?

`dpopp` repo isn't using `tulons`, but we've been tracking some work related to Passport + Gitcoin Trust Bonus on the same project board

**Comment by shavinac** [comment]
Fix in `tulons-ts` package: https://github.com/tulons/tulons-ts/commit/efaf21ddfd97c69d5f9405b2b6558ce1478d10d0

Upgrade in gitcoin web: https://github.com/gitcoinco/web/commit/37c2b7845f278edd0c05afa0e1929325df51ff81
