### ISSUE TITLE
🐛 [BUG]: User unable to save stamp VC to passport when their VPN turned on

### ISSUE THREAD

**Issue by farque65** [gitcoinco/dPopp#219]
- Kevin Olsen brought this up in Passport DevOps channel
"Yeah, came in with the VPN and was caught in the error state (hard refreshed included) until I noticed the VPN, switched it off and it worked. It was reproduceable for me with speed throttling (fast 3G) on in the inspector. "

**Comment by leoneric** [comment]
I successfully issued a Google stamp via a VPN connection
