### ISSUE TITLE
🐛 [BUG] Empty passports (like `{}`) seem to be loaded in some cases

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/dPopp#227]
![Image](https://user-images.githubusercontent.com/8137830/174043723-064430ff-e402-485b-b695-8a4ea536caea.png)

**Comment by shavinac** [comment]
5fa2cd1f822c86fd6f757ad928c5f7b31a44778d deployed to prod Thu, 16 Jun 2022 19:49:49 GMT
