### ISSUE TITLE
[UI] Communication - must be on the right network

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/dPopp#229]
It seems that for Bob the passport was not lost, but he has switched networks:
- he created the stamp on Eth but then switched to Polygon
- fact is
   - the user must be connected to the same network when he is verifying his trust bonus

**Important:** - the trust bonus page always loads the passport "from" mainnet (i. e. it specifies the mainnet chain id in the DID). So if the user created his passport while being on another chain, we will not load that.

According to the logs we do have users using different chains - these users will not have their passports loaded in the trust bonus page:

![Image](https://user-images.githubusercontent.com/8137830/174063141-cda29305-f4c1-42b8-92a6-1c6fd0dc1d6e.png)

Open point:
- shall we communicate this to the user more clearly? I think this is currently a user trap.

**Comment by shavinac** [comment]
Closed by #233
