### ISSUE TITLE
🐛 [BUG] Trust bonus calculation might hang ...

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/dPopp#230]
We have 1800+ users with this status:

![Image](https://user-images.githubusercontent.com/8137830/174065850-7ea8e66c-9a54-47e3-ae0e-e36b2adcbe96.png)

**Comment by nutrina** [comment]
The issue seems to have been caused by:
- misconfiguration of the trust bonus calculation options (brightid provider was missing)
- not properly handling errors and not tracking an error state for failures in the trust bonus calculation

The above points are now fixed and deployed.

**Comment by Zagorrrr** [comment]
@

**Comment by Zagorrrr** [comment]
0xDD7F7a0A7ca0434474Cd334c5403f4c1e83D3d47
