### ISSUE TITLE
🐛 [BUG]: Mainnet Ceramic node failing to load Passport schema stream

### ISSUE THREAD

**Issue by brentmartin** [gitcoinco/dPopp#238]
When attempting to fetch Passport definition stream from our mainnet node, requests keep returning 504 (Gateway timeout)

This is likely causing, or related to, inability to create new passports at this time

```
curl --location --request GET 'https://ceramic.passport-iam.gitcoin.co/api/v0/streams/kjzl6cwe1jw148h1e14jb5fkf55xmqhmyorp29r9cq356c7ou74ulowf8czjlzs'
```

---

Seems to be resolved after a manual container restart by dev team - thinking about ways to be able to automatically detect unresponsiveness like this

**Comment by shavinac** [comment]
Closing -- no action items
