### ISSUE TITLE
[BUG] Error time data does not match format

### ISSUE THREAD

**Issue by kevinrolsen** [gitcoinco/dPopp#251]
https://discord.com/channels/562828676480237578/988310248769069087

**Comment by nutrina** [comment]
A PR is pending here:  https://github.com/gitcoinco/web/pull/10690

**Comment by bobjiang** [comment]
another one.

I am having the attached issue while trying to save my passport progress. It gives this everytime I try. I have tried different devices, browsers and even tried signing it with both pc and mobile wallet apps but it always gives this issue.

1. Gitcoin User Profile: @kingler9067
2. Wallet Address: 0x093d5865681eBA0fbB91Dff70C6779504Fd1058d

What can I do to fix this and save my progress? Any help will be highly appreciated.

**Comment by kevinrolsen** [comment]
Still seeing users in production with this error. 
https://discord.com/channels/562828676480237578/988310248769069087/988787792177934387
https://discord.com/channels/562828676480237578/988310248769069087/989076800154005534

**Comment by nutrina** [comment]
The fix was deployed now, waiting for confirmations from users that this error does not appear any more.
