### ISSUE TITLE
[UI chore] Update to Ceramic error message on passport.gitcoin.co

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/dPopp#263]

**Comment by Etovardesign** [comment]
@leoneric 

Figma: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=2528%3A46587

**Comment by leoneric** [comment]
Note that we should use the "Ceramic Network Error" text from the Trust Bonus experience.

**Comment by shavinac** [comment]
added in https://github.com/gitcoinco/dPopp/commit/aa9188f7a49d905f84bd48cdc696ff83a77af010
