### ISSUE TITLE
Create and expose a 404 page to handle unrecognised paths

### ISSUE THREAD

**Issue by gdixon** [gitcoinco/dPopp#66]
Fleek will attempt to load documents from IPFS using a directory structure, if the user navigates to a page other than the index they will be met with an ugly 404 page. 

As a fallback, fleek will attempt to serve `/ipfs-404.html` when it can't otherwise find the desired document. 

We should create and store a custom  `/ipfs-404.html` document in the nextjs `out` directory at build time.

---

More information can be found here: https://docs.fleek.co/hosting/troubleshooting/#adding-404-errors

**Comment by luke-focusedlabs** [comment]
Updated and changes are pushed, good catches!

**Comment by yonocan** [comment]
The 404 still isn't fitting on the page. Can we make the image a bit smaller? It looks like it's bigger than it was before. We can also tighten the spacing between 404 Error and the text below. 

![Image](https://user-images.githubusercontent.com/5656217/171641119-bc894f8c-7727-48b2-b8ba-8f1112a11784.png)

**Comment by luke-focusedlabs** [comment]
Can you send me the dimensions of your screen? I tested on an ultrawide, normal 1080p screen, and mobile phones both vertical and horizontal. If you send me the dimensions I can more finely tune the image

**Comment by brentmartin** [comment]
Moving this to accepted, but opening #142 to be reviewed at a later date.
