### ISSUE TITLE
🎫 [STAMPS] As a passport holder, I can add a POAP stamp to my passport

### ISSUE THREAD

**Issue by brentmartin** [gitcoinco/dPopp#67]
GIVEN that I have signed into my passport with a wallet address
WHEN I click the POAP stamp
THEN I sign a message in my wallet to sign (checks my address for POAP's w/ +15 days)

**Success**:
THEN I see a modal that includes my address that my POAP were checked against with a check mark, and info on how we verify them (at least 15 days)
AND WHEN I click "verify"
THEN Metamask sends me a verify POAP's message to sign
AND WHEN I sign the message on Metamask
THEN my POAP stamp shows that I am verified

**Failed**:
THEN I see a modal that includes my address that my POAP were checked against with an x mark, and info on how we verify them (at least 15 days)
AND WHEN I click "Go Back"
THEN It returns to my passport page

**Notes**
- Would like to combine the two modal messages that the Trust Bonus Score modal uses into one message - just a success or failed modal
- Trust Bonus Score messages in the modal: 1. explains what POAP's are, how we verify them (at least 15 days) and 2. shows address the user is signed in to that we'll check and prompts user to check.

**Questions**
- Why does it send a message for Metamask to sign on POAP, but not on ENS when verifying?

**Comment by brentmartin** [comment]
For acceptance criteria - this failed at finding a POAP with an associated ETH address

**Comment by brentmartin** [comment]
@farque65 and I looked at how we're doing the UI of modals and believe there is a few user flow issues

Making some changes to the AC to reflect those issues

Changing the AC from:
> GIVEN that I have signed into my passport with a wallet address
> WHEN I click the POAP stamp
> THEN I see a message that explains what POAP's are, how we verify them (at least 15 days), and the address the user is signed in to that we'll check.
> AND WHEN I click "verify"
> THEN Metamask sends me a verify pop badges message to sign
> AND WHEN I sign the message on Metamask
> THEN my POAP stamp shows that I am verified

to

> GIVEN that I have signed into my passport with a wallet address
> WHEN I click the POAP stamp
> THEN I sign a message in my wallet to sign (checks my address for POAP's w/ +15 days)
> 
> **Success**:
> THEN I see a modal that includes my address that my POAP were checked against with a check mark, and info on how we verify them (at least 15 days)
> AND WHEN I click "verify"
> THEN Metamask sends me a verify POAP's message to sign
> AND WHEN I sign the message on Metamask
> THEN my POAP stamp shows that I am verified
> 
> **Failed**:
> THEN I see a modal that includes my address that my POAP were checked against with an x mark, and info on how we verify them (at least 15 days)
> AND WHEN I click "Go Back"
> THEN It returns to my passport page

**Comment by brentmartin** [comment]
Heres a quick drawn-out idea of what we're thinking:

Success state is something like this:
![Image](https://user-images.githubusercontent.com/5798446/171507258-df16f459-67ed-4315-9643-d2642dc919a3.png)

Failed state is something like this:
![Image](https://user-images.githubusercontent.com/5798446/171507290-a8a557b6-cbb9-40ad-a617-e92baaa11be7.png)

**Comment by nutrina** [comment]
PR is open: https://github.com/gitcoinco/dPopp/pull/138

**Comment by brentmartin** [comment]
closing this issue, and moving it to accepted along with #138 as it reflects the mock-ups in the figma file
