### ISSUE TITLE
🚗 [GRANTS] As a Gitcoin user, I want to connect my wallet, so that I can access my passport for GR14

### ISSUE THREAD

**Issue by yonocan** [gitcoinco/dPopp#77]
GIVEN that I am a Gitcoin user with a Gitcoin account
WHEN I visit the Trust Bonus page
THEN I see a button to connect with my passport
AND WHEN I click that button
THEN I am prompted to connect my wallet 
AND WHEN I have a passport
THEN I am connected

AND WHEN I don’t have a passport
THEN I am prompted to create a passport 
AND WHEN I click "Create Passport" 
THEN I am taken to the passport creation flow in a new tab
AND WHEN I complete that process AND I come back to Gitcoin
THEN I see that my passport is connected

**Mocks**
- Landing page for Trust Bonus dPopp in Gitcoin.co: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=1735%3A44330
- Modal that prompts users to connect their wallet: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=1751%3A45392
- Modal for no passport found: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=1735%3A44959
- Landing page for passport verified: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=1735%3A44505

**Comment by yonocan** [comment]
@gdixon 
When I click "Why this Matters" on the Trust Bonus page, I see a header that says "why this matters modal." It looks like the video won't play. 

![Image](https://user-images.githubusercontent.com/5656217/170718967-413f346c-ba79-4dcd-996e-b67f634a9ae8.png)

**Comment by brentmartin** [comment]
video is playing for me on https://review-10618.review.gitcoin.co/trust
