### ISSUE TITLE
🎨 [UI] As a user, I want to see a redesigned logged-in landing page, so that I can clearly see what stamps I have verified

### ISSUE THREAD

**Issue by yonocan** [gitcoinco/dPopp#79]
GIVEN that I have a passport
WHEN I am authenticated with a wallet
THEN I can see an updated passport stamp page

**Notes**
- Change background colors
- Update stamp format

**Mocks**
- https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=1735%3A44680

**Comment by brentmartin** [comment]
Changes to make:
- add svg icons to the stamps
- Gitcoin header should be aligned with the wallet dropdown
- Subheader "Decentralized Identity Verification" should be aligned with the "Passport JSON" button

Questions:
- is there supposed to be a nav bar here that contains the Gitcoin header on left and wallet dropdown on right? @Etovardesign


![Image](https://user-images.githubusercontent.com/5798446/170100827-f0c0b9b3-2201-42eb-8d2f-c1c04260e522.png)

**Comment by brentmartin** [comment]
After updates, here's where we are.

Changes to make:

- ~add svg icons to the stamps~
- Gitcoin header should be aligned with the wallet dropdown
- Subheader "Decentralized Identity Verification" should be aligned with the "Passport JSON" button

We still have questions around the Nav bar and Subheader.
