### ISSUE TITLE
🎨 [UI] As a user, I want the JSON block associated with my passport to be hidden, so that I can more clearly see my stamps

### ISSUE THREAD

**Issue by yonocan** [gitcoinco/dPopp#82]
GIVEN that a user has created a passport
WHEN they are on the passport landing page
THEN the JSON attached to a passport should be hidden in the UI 
AND WHEN the user clicks on the call to action or prompt
THEN they can see the JSON

**Mocks**
- Modal for Passport JSON: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=1735%3A44092
- Stamps landing page with button for passport modal: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=1735%3A44680

**Notes**
-

**Comment by brentmartin** [comment]
Changes needed:

- remove the dropdown to reflect the layout in Figma
- take the text used for dropdown, and place it under the header in the modal

Questions:
- Should there be a fixed height on modals? @Etovardesign 

Figma mocks:

![Image](https://user-images.githubusercontent.com/5798446/170101874-54be7745-c627-4f66-b8d8-4067c4f794b4.png)


Staging:

![Image](https://user-images.githubusercontent.com/5798446/170101925-43dc692b-a403-4f86-ad77-fb986d90b434.png)
![Image](https://user-images.githubusercontent.com/5798446/170101926-de45cfb9-6395-4e8f-9d8b-ecea2ab2e511.png)
